version: "3.4"

services:
    api:
        build:
          context: .
          dockerfile: WebAPI/Dockerfile
        ports:
          - "7274:7274"
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"

        environment:
            SA_PASSWORD: "?#G3#bJCSfo7R#&d"
            ACCEPT_EULA: "Y"